# Generated by Django 5.1 on 2024-10-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='upload',
        ),
    ]
