# Generated by Django 5.1 on 2024-10-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_notes_options_remove_notes_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
