# Generated by Django 5.1 on 2024-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'WikipediaList',
                'verbose_name_plural': 'WikipediaList',
            },
        ),
    ]
