# Generated by Django 5.1 on 2024-10-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Null', max_length=140)),
                ('description', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('introduction', models.TextField()),
                ('content', models.TextField()),
                ('conclusion', models.TextField()),
            ],
            options={
                'verbose_name': 'Assignments',
                'verbose_name_plural': 'Assignments',
            },
        ),
    ]
